"""Initial migration12

Revision ID: cbca3c033e7f
Revises: 979c2f782c41
Create Date: 2025-01-29 13:55:53.133046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbca3c033e7f'
down_revision: Union[str, None] = '979c2f782c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('content', sa.String(), nullable=True))
    op.drop_index('ix_cards_description', table_name='cards')
    op.create_index(op.f('ix_cards_content'), 'cards', ['content'], unique=False)
    op.drop_column('cards', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('description', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_cards_content'), table_name='cards')
    op.create_index('ix_cards_description', 'cards', ['description'], unique=False)
    op.drop_column('cards', 'content')
    # ### end Alembic commands ###
